#include "assembler.h"
#include "mu-mips.h"
/* This function reads the string returned for each line within the file. It converts the instruction string into 
all of a MIPS instructions parts. This is achieved by parsing each portion of the string into seperate strings. It may
be worth looking into making this function recursive for calls on a single string and returning each part of the string in one call.
*/
const char** readString(char* input)
{
    char** masterArray = NULL; 
    char* token;
    masterArray = malloc(sizeof(char *)* 6);
    for(int i = 0; i < 6; i++)
    {
        masterArray[i] = malloc(sizeof(char)*10);
        if(masterArray[i] == NULL)
        {
            perror("Memory cannot accomodate any more allocations of this size!\n****Exiting now****");
            exit(EXIT_FAILURE);
        }
    }
    token = strtok(input, " ");
    for(int i = 0; token != NULL; i++)
    {
        strcpy(masterArray[i], token);
    }
    return masterArray;
} 
/* This function reads in each line of the input file and feeds it to the readString function which will in turn 
feed the input lines to teh other functions implemented in this program. It will return a single string that
is the maximum character length of a MIPS isntruction 
*/
const char* readLine(FILE* fp)
{
    
}
/*This instruction takes the first part of the instrcuction (the beginning of the string until a space is reached)
and using this information formulates the opcode and/or funct.
*/
const char* instToBin(char* input)
{

}
/* This function converts each part of the string that represents a register into its corresponding binary value.
It takes in the text representation of a MIPS instruction and operates on this data to return the proper binary
*/
const char* regToBin(char* input)
{

}
/*This function converts the hexadecimal immediate value into a binary representation and returns that as a string.
This will only be used in certain instructions (i.e. immediate or I-type instructions)
*/
const char* immToBin(char* input)
{

}
/*this will convert the target address used in j-type instructions to a binary string that can be concatenated 
onto the end of the rest of the binary string.
*/
const char* tarToBin(char* input)
{

}
/*This function will concatenate all the strings generated by the other functions into one long string that can 
transform all of them into one readable binary string that can be converted into a hexadecimal number. 
*/
const char* stringToBin(char* input)
{

}
/*This function will convert the final string product of the string to bin function into a hexadecimal number. 
It is possible for this function to convert any binary string of any length into a hexadecimal so long as it
can fit within a 32-bit hexadecimal.
*/
uint32_t binToHex(char* input)
{

}
int main()
{

}